export const theme = {
  fonts: {
    regular: 'Poppins-Regular',
    medium: 'Poppins-Medium',
    headingBold: 'Poppins-Bold',
    semiBold: 'Inter-SemiBold',
  },
  fontSize: {
    xs: 10,
    sm: 12,
    base: 14,
    md: 16,
    lg: 18,
    xl: 24,
    '2xl': 30,
    '3xl': 36,
    '4xl': 48,
  },
  colors: {
    primary: '#6366F1',
    primaryLight: '#818CF8',
    primaryDark: '#4F46E5',
    secondary: '#10B981',
    secondaryLight: '#34D399',
    accent: '#F59E0B',
    accentLight: '#FBBF24',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    surfaceLight: '#F1F5F9',
    green: {
      light: '#ECFDF5',
      medium: '#A7F3D0',
      dark: '#34D399',
    },
    red: {
      light: '#FEF2F2',
      medium: '#FCA5A5',
      dark: '#F87171',
    },
    yellow: {
      light: '#FFFBEB',
      medium: '#FDE68A',
      dark: '#FBBF24',
    },
    blue: {
      light: '#EFF6FF',
      medium: '#BFDBFE',
      dark: '#60A5FA',
    },
    white: '#FFFFFF',
    black: '#000000',
    gray: {
      light: '#F3F4F6',
      medium: '#D1D5DB',
      dark: '#9CA3AF',
    },
    text: {
      primary: '#1E293B',
      secondary: '#64748B',
      light: '#94A3B8',
      inverse: '#FFFFFF',
    },
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
    purple: '#8B5CF6',
  },
  layout: {
    horizontalPadding: 20,
    verticalPadding: 16,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 20,
    full: 9999,
  },
  typography: {
    fontFamily: {
      regular: 'Inter-Regular',
      medium: 'Inter-Medium',
      semiBold: 'Inter-SemiBold',
      bold: 'Inter-Bold',
      headingRegular: 'Poppins-Regular',
      headingMedium: 'Poppins-Medium',
      headingSemiBold: 'Poppins-SemiBold',
      headingBold: 'Poppins-Bold',
    },
    fontSize: {
      xs: 10,
     sm: 12,
    base: 14,
    lg: 18,
    xl: 24,
    '2xl': 28,
      '3xl': 30,
      '4xl': 36,
    },
    lineHeight: {
      xs: 16,
      sm: 20,
      base: 24,
      lg: 28,
      xl: 32,
      '2xl': 36,
      '3xl': 40,
      '4xl': 44,
    },
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.15,
      shadowRadius: 15,
      elevation: 5,
    },
  },
  zIndex: {
    dropdown: 10,
    modal: 20,
    toast: 30,
  },
  tabBar: {
    height: 56, // Added tabBar property for safe referencing
  },
  buttons: {
    primary: {
      backgroundColor: '#6366F1',
      textColor: '#FFFFFF',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
    },
    secondary: {
      backgroundColor: '#10B981',
      textColor: '#FFFFFF',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
    },
    outline: {
      borderColor: '#6366F1',
      borderWidth: 1,
      textColor: '#6366F1',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
    },
  },
  inputs: {
    default: {
      backgroundColor: '#FFFFFF',
      borderColor: '#E2E8F0',
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: '#1E293B',
    },
  },
  modals: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadow: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 10,
    },
  },
} as const;

export type Theme = typeof theme;